### ISSUE TITLE
tmux colors

### ISSUE THREAD

**Issue by maheshsundaram** [pineapplegiant/spaceduck#11]
Hi there! I really love this colorscheme - and so I want it everywhere.

It looks like in the README screenshot you use tmux and also have styled it with the spaceduck colors?

I took my best guess and what you are probably using. Maybe it could be added to the README?

```
set-option -g default-terminal "screen-256color"
set-option -g status-style bg='#30365f',fg='#16172d'
set-option -g window-status-current-style bg='#7a5ccc',fg='#ecf0c1'
set-option -g message-style bg='#7a5ccc',fg='#ecf0c1'
set-option -g message-command-style bg='#7a5ccc',fg='#ecf0c1'
```

![screen07](https://user-images.githubusercontent.com/9041312/103708500-c40d8680-4f54-11eb-84ab-7c9e5fb2a4ef.jpg)

**Comment by pineapplegiant** [comment]
That's a great idea. Yeah I've been procrastinating on adding this. 
I wasn't aware that you could use hexadecimal colors? I'm searching now– it looks like Tmux just approximates the colors which makes it much easier: [https://github.com/tmux/tmux/issues/315](https://github.com/tmux/tmux/issues/315).

I currently have the lighter purple on my status bar to differentiate from the lightline theme status bar, but I think I'll add screenshots and snippets with both variations, since I like the dark one you have too. 

Thanks for sharing your config! I'll work on adding it in this week.

<img width="1552" alt="Screen Shot 2021-01-05 at 4 23 04 PM" src="https://user-images.githubusercontent.com/32819563/103710603-a64f1a00-4f72-11eb-98f3-0825e1f5d940.png">

**Comment by pineapplegiant** [comment]
Okay, scratch that. I'm silly it definitely supports truecolor. This is what I've come up with for powerline-looking styles for now: Dark, Default, and Purple. I'm going to add the files to the [spaceduck-terminal](https://github.com/pineapplegiant/spaceduck-terminal) repo and link it on this README @maheshsundaram. 

<img width="961" alt="dark" src="https://user-images.githubusercontent.com/32819563/104108262-5a58e980-5280-11eb-8757-1b809b41da5c.png">

<img width="961" alt="default" src="https://user-images.githubusercontent.com/32819563/104108263-5cbb4380-5280-11eb-8cc8-739f1df2b6e4.png">

<img width="961" alt="purple" src="https://user-images.githubusercontent.com/32819563/104108280-75c3f480-5280-11eb-9074-4a2129eca3a4.png">

**Comment by maheshsundaram** [comment]
@pineapplegiant Looks really nice, thank you for your work and for sharing!

**Comment by pineapplegiant** [comment]
Let me know what you think!
[https://github.com/pineapplegiant/spaceduck-terminal/tree/main/tmux](https://github.com/pineapplegiant/spaceduck-terminal/tree/main/tmux)
