### ISSUE TITLE
I made a duckduckgo port, but I am unsure where to put it

### ISSUE THREAD

**Issue by YoussefBouzekri** [pineapplegiant/spaceduck#31]
Hey, thanks for the great theme !
I made this space**duck** theme for **duck**duckgo (how ironic lol) but I am not sure if I should put it in the official repo (it may become too crowded) or in spaceduck-terminal (this one is for terminal ports only)

Here is how it looks :
![image](https://user-images.githubusercontent.com/77839865/117014689-f18ef480-ace8-11eb-8d81-796fdc668082.png)

to get it you need to navigate to the settings > click `load settings` on the right side > type `spaceduck-ddg` > save and exit.
![image](https://user-images.githubusercontent.com/77839865/117015338-87c31a80-ace9-11eb-81c8-1ed4c368bac5.png)

**Comment by pineapplegiant** [comment]
Sorry for getting to you late @YoussefBouzekri! 
Would you like to be the owner of this code? You can create a repo, and I'll add a link to the readme. The only other option would be me to host the code and link here and have you as a contributor. This repo's for the vim/neovim plugin so obviously putting it here wouldn't be good. Let me know what you think? 

I've also thought of creating an organization too since I've been getting a lot of ports...idk

**Comment by YoussefBouzekri** [comment]
@pineapplegiant I would love to manage the repo (will be a great learning experience for me since I have never worked on a serious open-source project before), you could then link to that repo in this repo's README and move all of the ports to the new "Spaceduck Ports" repo so that it doesn't get too confusing

**Comment by YoussefBouzekri** [comment]
idk if you know about it but there is also a [firefox theme](https://addons.mozilla.org/en-US/firefox/addon/spaceduck/), I didn't know the theme was everywhere lol 🤣

**Comment by pineapplegiant** [comment]
That sound like a great idea! Yeah luckily I got an email from the firefox theme creator telling me about it, so I wasn't too surprised. I've been meaning to add that link here. Yeah we'd love to have you as a contributor! 

Definitely will bug you when the two other variant color scheme variants come out both light and middle contrast themes, so you can add that in. I might ask you to change the scheme a bit too, I feel like cyan is a good default link color, but that's personal preference of course!

**Comment by YoussefBouzekri** [comment]
![image](https://user-images.githubusercontent.com/77839865/117488865-cc0e1f00-af64-11eb-924c-1b0bb5da9d30.png)
I feel like this is too much blue/purple idk.. I'll keep it if you prefer this

I must say this in advance , I might not be able to do much work on the repo these next few weeks until the summer vacation (mid june where I live) because of final exams, I will try to do my best tho 🦆

**Comment by pineapplegiant** [comment]
Hmm yeah. Maybe Blue on the title and gray  as the url or something. Just matching googles vibe basically idk. 

And that’s no worries don’t fail because of spaceduck! Spaceduck devs are A students. If you want you can give me collaborator access on a dev branch like how I have for @jinh0 hehe

**Comment by YoussefBouzekri** [comment]
Alright I'll start working on it !

**Comment by pineapplegiant** [comment]
Hey @YoussefBouzekri I think I might have miscommunicated with you and I apologize 😢 . I saw you created a whole repo for spaceduck-ports. I wanted to say thank you, but I was thinking you should just self-host the duckduckgo theme and I'll link to it from here. It might be a little overkill to have a repo for just ports.

As far as where to put the link, I thought about it, and it makes sense to follow how Neovim has and start a wiki, especially since the readme is getting a little long! 

https://github.com/neovim/neovim/wiki/Related-projects
