### ISSUE TITLE
Consider tweaking the comments color

### ISSUE THREAD

**Issue by fdidron** [pineapplegiant/spaceduck#34]
Hello,

I absolutely love this color theme. However one issue I have with it is the comments color is a bit too dark, making the comments hardly visible.

Tweaking the comments color to a slighlty brighter color goes a long way IMHO (window on the bottom contains the tweak)

![comments](https://user-images.githubusercontent.com/1848786/118898408-70219e00-b947-11eb-8124-1443f47d28ed.jpg)

Now this is probably a matter of opinion :) Happy to make a PR if you think it is worth it

**Comment by pineapplegiant** [comment]
Hey! Thanks for this. Yes you’re absolutely right. I’ve been super procrastinating on many things, but this one is a must. We have changed the comment color along with some other things on our dev branch!

Like instead of main try out dev and tell me what you think. I’m in the process of finalizing colors still so I’ll keep this open until I merge into main.

**Comment by fdidron** [comment]
@pineapplegiant  Just tried the dev branch, that's perfect !

**Comment by Nargonath** [comment]
Thanks for raising this, it's been on my mind lately too. That's cool to see that you already took care of it @pineapplegiant . 💪

**Comment by jinh0** [comment]
For any future developers who have similar complaints of dark comment color or cursor line color, **please use the `dev` branch of the colorscheme until version 0.1 is released to the main branch.**

This can be done as follows using a plugin manager like `vim-plug`: 
```
Plug 'pineapplegiant/spaceduck', { 'branch': 'dev' }
```
