### ISSUE TITLE
Wrong highlight in Python

### ISSUE THREAD

**Issue by Eliot00** [pineapplegiant/spaceduck#39]
## Screenshot: 

<img width="481" alt="截屏2021-05-27 下午5 25 48" src="https://user-images.githubusercontent.com/18375468/119801966-b9a65600-bf10-11eb-8955-2f10510b9c9a.png">

## Test code:

```python
import sys
from random import choice

print("hello world!")

def func():
    try:
        a = {'foo': 'bar'}
    except:
        raise KeyError

class Foo:
    def __init__(self, words: list[str]) -> int:
        return len(words)

async def io():
    return await google()
```

## Plugin:

[python-syntax](https://github.com/vim-python/python-syntax)

**Comment by jinh0** [comment]
Python syntax has been the trickiest to deal with due to the reason @pineapplegiant has mentioned: Python syntax highlighting is **horrible** on Vim, and no plugin has successfully managed to handle it.

<img width="660" alt="Screen Shot 2021-05-31 at 12 12 38 PM" src="https://user-images.githubusercontent.com/40512164/120135003-464f5d80-c20a-11eb-9779-cf03a417a003.png">

This is the best fix I could come up with. What do you think?

Also, as much as I like consistency between languages, Python is so drastically "Pythonic" that it requires a different orientation from JavaScript colors.

Also, @Eliot00 , having tried out `python-syntax`, I don't think it gives any extra features over over [vim-polyglot](https://github.com/sheerun/vim-polyglot)'s python syntax. In fact, I think `python-syntax` is worse than polyglot.

**Comment by Eliot00** [comment]
> Python syntax has been the trickiest to deal with due to the reason @pineapplegiant has mentioned: Python syntax highlighting is **horrible** on Vim, and no plugin has successfully managed to handle it.
> 
> <img alt="Screen Shot 2021-05-31 at 12 12 38 PM" width="660" src="https://user-images.githubusercontent.com/40512164/120135003-464f5d80-c20a-11eb-9779-cf03a417a003.png">
> 
> This is the best fix I could come up with. What do you think?
> 
> Also, as much as I like consistency between languages, Python is so drastically "Pythonic" that it requires a different orientation from JavaScript colors.
> 
> Also, @Eliot00 , having tried out `python-syntax`, I don't think it gives any extra features over over [vim-polyglot](https://github.com/sheerun/vim-polyglot)'s python syntax. In fact, I think `python-syntax` is worse than polyglot.

thanks, I'll try the vim-polyglot
